Repository GreenBlitz/GBScouting, pull requests merged in 2025-01, with the labels that each got.

#37 Reef config
  application/src/components/QRCode-Generator.tsx
  application/src/scouter/MatchList.tsx
  application/src/scouter/ScouterInputs.ts
  application/src/scouter/ScoutingTab.tsx
  application/src/scouter/input-types/CheckBoxedSliderInput.tsx
  application/src/scouter/input-types/MapInput.tsx
  application/src/scouter/tabs/Autonomous.tsx
  application/src/scouter/tabs/PostMatch.tsx
  application/src/scouter/tabs/PreMatch.tsx
  application/src/scouter/tabs/Teleoperated.tsx
  application/src/strategy/TeamTab.tsx
  application/src/utils/Crescendo.ts
  application/src/utils/Match.ts
  application/src/utils/SeasonUI.ts
  application/src/utils/Serde.ts
Labels: New Feature, Frontend, Improvement

#39 Reef score form
  .gitignore
  application/src/components/ReefForm.tsx
  application/src/components/reefScore.css
  application/src/scouter/ScouterInputs.ts
  application/src/scouter/tabs/Teleoperated.tsx
Labels: New Feature, Frontend

#42 Tailwind & UI Improvements
  application/index.html
  application/package.json
  application/postcss.config.js
  application/src/App.tsx
  application/src/components/CancelConfirmation.tsx
  application/src/components/PageTransition.tsx
  application/src/index.css
  application/src/scouter/ScouterInput.tsx
  application/src/scouter/ScoutingTab.tsx
  application/src/scouter/input-types/CheckBoxedSliderInput.tsx
  application/src/scouter/input-types/CheckboxInput.tsx
  application/src/scouter/input-types/CounterInput.tsx
  application/src/scouter/input-types/DropdownInput.tsx
  application/src/scouter/input-types/NumberInput.tsx
  application/src/scouter/input-types/RadioInput.tsx
  application/src/scouter/input-types/TextInput.tsx
  application/src/scouter/tabs/PreMatch.tsx
  application/tailwind.config.js
Labels: New Feature, Frontend, Improvement

#41 Better options in Dropdown and Radio
  application/src/scouter/input-types/DropdownInput.tsx
  application/src/scouter/input-types/RadioInput.tsx
Labels: Frontend, Improvement

#50 Autonomous map
  application/src/index.css
  application/src/main.tsx
  application/src/scouter/ScouterInputs.ts
  application/src/scouter/input-types/auto-map/AlgaeButton.tsx
  application/src/scouter/input-types/auto-map/AutonomousMapInput.tsx
  application/src/scouter/input-types/auto-map/CoralButton.tsx
  application/src/scouter/input-types/auto-map/SushiButton.tsx
  application/src/scouter/tabs/Autonomous.tsx
  application/src/utils/FolderStorage.ts
Labels: New Feature, Frontend

#54 Bakground Bug
  application/index.html
  application/src/App.css
  application/src/App.tsx
  application/src/assets/greenblitz.svg
  application/src/scouter/ScouterInput.tsx
  application/src/scouter/tabs/ScouterPreMatch.tsx
Labels: bug, Frontend, Improvement

#55 Small improvement to endgame
  application/src/strategy/team-tab/sections/StrategyEndgame.tsx
Labels: bug, Frontend, Improvement

#51 Reef + Algea Panel
  application/src/components/ReefForm.tsx
  application/src/components/teleopForm.tsx
  application/src/scouter/ScouterInputs.ts
  application/src/scouter/tabs/ScouterTeleoperated.tsx
Labels: New Feature, Frontend

#57 Better UI In Scouter
  application/src/components/teleopForm.tsx
  application/src/scouter/ScouterInputs.ts
  application/src/scouter/tabs/ScouterAutonomous.tsx
Labels: Frontend, Improvement

#58 Strategy Improvements
  application/src/TeamData.ts
  application/src/components/teleopForm.tsx
  application/src/scouter/ScouterInputs.ts
  application/src/strategy/charts/AutoChart.tsx
  application/src/strategy/team-tab/TeamTab.tsx
  application/src/strategy/team-tab/sections/StrategyAutonomous.tsx
  application/src/strategy/team-tab/sections/StrategyEndgame.tsx
  application/src/strategy/team-tab/sections/StrategyTeleoperated.tsx
  application/src/utils/Match.ts
  application/src/utils/SeasonUI.ts
Labels: Frontend, Improvement

#46 General Tab Improvement
  application/src/App.tsx
  application/src/TeamData.ts
  application/src/strategy/GeneralTab.tsx
  application/src/strategy/charts/TableChart.tsx
  application/src/strategy/general-tab/GeneralTab.tsx
  application/src/strategy/general-tab/GeneralTable.css
Labels: Frontend, Improvement

#59 Itay Feedback
  application/src/TeamData.ts
  application/src/components/reefScore.css
  application/src/components/teleopForm.tsx
  application/src/scouter/ScouterInputs.ts
  application/src/scouter/ScoutingTab.tsx
  application/src/scouter/tabs/ScouterAutonomous.tsx
  application/src/scouter/tabs/ScouterPostMatch.tsx
  application/src/scouter/tabs/ScouterTeleoperated.tsx
  application/src/strategy/charts/CoralChart.tsx
  application/src/strategy/charts/LinearHistogramChart.tsx
  application/src/strategy/charts/PercentageBarChart.tsx
  application/src/strategy/general-tab/GeneralTab.tsx
  application/src/strategy/general-tab/GeneralTable.css
  application/src/strategy/team-tab/TeamTab.tsx
  application/src/strategy/team-tab/sections/StrategyTeleoperated.tsx
  application/src/utils/Fetches.ts
Labels: Frontend, Improvement
