Repository GreenBlitz/GBScouting, pull requests merged in 2025-02, with the labels that each got.

#61 Better Scouter Side
  application/src/App.css
  application/src/App.tsx
  application/src/TeamData.ts
  application/src/assets/branch-right.svg
  application/src/assets/branch.svg
  application/src/assets/low-algea.svg
  application/src/assets/low-coral.svg
  application/src/assets/reef.png
  application/src/components/CancelConfirmation.tsx
  application/src/components/reefScore.css
  application/src/components/teleopForm.tsx
  application/src/scouter/ScouterInputs.ts
  application/src/scouter/ScoutingTab.tsx
  application/src/scouter/input-types/ReefInput.tsx
  application/src/scouter/input-types/ReefPickInput.tsx
  application/src/scouter/tabs/ScouterAutonomous.tsx
  application/src/scouter/tabs/ScouterTeleoperated.tsx
  application/src/strategy/team-tab/TeamTab.tsx
  application/src/utils/SectionHandler.ts
  application/src/utils/Utils.ts
Labels: New Feature, Frontend, Improvement

#60 TBA implement --> core
  .gitignore
  application/package.json
  application/server.ts
  application/src/utils/Fetches.ts
Labels: New Feature, Backend

#64 QOL Improvements
  application/server.ts
  application/src/TeamData.ts
  application/src/components/teleopForm.tsx
  application/src/scouter/ScouterInput.tsx
  application/src/scouter/ScouterInputs.ts
  application/src/scouter/ScoutingTab.tsx
  application/src/scouter/input-types/ReefInput.tsx
  application/src/scouter/input-types/ReefPickInput.tsx
  application/src/scouter/tabs/ScouterPostMatch.tsx
  application/src/strategy/charts/AutoChart.tsx
  application/src/strategy/charts/LineChart.tsx
  application/src/strategy/charts/LinearHistogramChart.tsx
  application/src/strategy/charts/PercentageBarChart.tsx
  application/src/strategy/charts/ReefChart.tsx
  application/src/strategy/charts/TableChart.tsx
  application/src/strategy/general-tab/GeneralTab.tsx
  application/src/strategy/team-tab/TeamTab.tsx
  application/src/strategy/team-tab/sections/StrategyTeleoperated.tsx
  application/src/utils/Match.ts
Labels: Frontend, Improvement

#65 Box plot
  application/src/scouter/input-types/ReefInput.tsx
  application/src/strategy/charts/BoxChart.tsx
  application/src/strategy/charts/LineChart.tsx
  application/src/strategy/team-tab/sections/StrategyAutonomous.tsx
  application/src/strategy/team-tab/sections/StrategyTeleoperated.tsx
Labels: New Feature, Frontend

#67 Improvements
  application/server.ts
  application/src/App.tsx
  application/src/TeamData.ts
  application/src/scouter/ScouterInputs.ts
  application/src/scouter/input-types/ReefPickInput.tsx
  application/src/scouter/input-types/reef-levels/ReefLevelsInput.tsx
  application/src/scouter/input-types/reef-levels/reefScore.css
  application/src/strategy/NoteTab.tsx
  application/src/strategy/charts/AutoChart.tsx
  application/src/strategy/charts/CoralChart.tsx
  application/src/strategy/charts/ReefChart.tsx
  application/src/strategy/team-tab/TeamTab.tsx
  application/src/utils/Fetches.ts
  application/src/utils/SeasonUI.ts
Labels: New Feature, Frontend, Backend, Improvement

#68 Team Comparison
  application/server.ts
  application/src/App.tsx
  application/src/TeamData.ts
  application/src/components/TeamPicker.tsx
  application/src/strategy/ComparisonTab.tsx
  application/src/strategy/charts/BoxChart.tsx
  application/src/strategy/team-tab/TeamTab.tsx
Labels: New Feature, Frontend

#69 Team choosing & Serde
  application/src/components/TeamPicker.tsx
  application/src/scouter/ScoutingTab.tsx
  application/src/scouter/input-types/ReefPickInput.tsx
  application/src/scouter/input-types/reef-levels/ReefLevelsInput.tsx
  application/src/strategy/ComparisonTab.tsx
  application/src/strategy/general-tab/GeneralTab.tsx
  application/src/utils/Serde.ts
  application/src/utils/Utils.ts
Labels: Frontend, Backend, Improvement

#70 Small features
  application/server.ts
  application/src/App.tsx
  application/src/TeamData.ts
  application/src/scouter/ScoutingTab.tsx
  application/src/scouter/input-types/reef-levels/ReefLevelsInput.tsx
  application/src/scouter/tabs/ScouterAutonomous.tsx
  application/src/scouter/tabs/ScouterTeleoperated.tsx
  application/src/strategy/ComparisonTab.tsx
  application/src/strategy/NoteTab.tsx
  application/src/strategy/charts/AutoChart.tsx
  application/src/strategy/general-tab/GeneralTable.css
  application/src/utils/Fetches.ts
  application/src/utils/SeasonUI.ts
  application/src/utils/Utils.ts
Labels: New Feature, Frontend, Backend, Improvement
